# Generated by Django 4.2.13 on 2026-08-20 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("equity", "0002_fund_investment"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "lp_type",
                    models.CharField(
                        choices=[
                            ("Endowment", "Endowment"),
                            ("Family Office", "Family Office"),
                            ("Pension Fund", "Pension Fund"),
                            ("Individual", "Individual"),
                            ("Corporate", "Corporate"),
                            ("Fund of Funds", "Fund of Funds"),
                        ],
                        default="Individual",
                        max_length=32,
                    ),
                ),
                ("commitment_cents", models.BigIntegerField(default=0)),
                ("contributed_cents", models.BigIntegerField(default=0)),
                ("distributions_cents", models.BigIntegerField(default=0)),
                ("nav_cents", models.BigIntegerField(default=0)),
                ("entry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lps",
                        to="equity.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
