# Generated by Django 4.2.13 on 2026-08-20 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equity", "0002_fund_investment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cashflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("call", "Capital Call"), ("dist", "Distribution")],
                        max_length=8,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "amount_cents",
                    models.BigIntegerField(
                        default=0, help_text="Positive cents; sign by type"
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflows",
                        to="equity.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
