# Generated by Django 4.2.13 on 2026-06-11 01:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("stock_certificate", "Stock Certificate"),
                            ("option_grant_letter", "Option Grant Letter"),
                            ("safe_agreement", "SAFE Agreement"),
                            ("board_consent", "Board Consent"),
                            ("83b_election", "83(b) Election Form"),
                            ("form_3921", "IRS Form 3921"),
                            ("409a_report", "409A Valuation Report"),
                            ("subscription_agreement", "Subscription Agreement"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending Signature"),
                            ("signed", "Signed"),
                            ("voided", "Voided"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/%Y/%m/"
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "docusign_envelope_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("docusign_status", models.CharField(blank=True, max_length=30)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("docusign_recipient_id", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
