# Generated by Django 4.2.13 on 2026-06-11 01:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("state_of_inc", models.CharField(default="Delaware", max_length=50)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("c_corp", "C-Corporation"),
                            ("s_corp", "S-Corporation"),
                            ("llc", "LLC"),
                            ("lp", "Limited Partnership"),
                        ],
                        default="c_corp",
                        max_length=20,
                    ),
                ),
                ("ein", models.CharField(blank=True, max_length=20)),
                ("date_incorporated", models.DateField(blank=True, null=True)),
                (
                    "fiscal_year_end",
                    models.CharField(default="12-31", help_text="MM-DD", max_length=5),
                ),
                (
                    "latest_409a_value",
                    models.BigIntegerField(
                        blank=True, help_text="FMV in cents", null=True
                    ),
                ),
                (
                    "latest_409a_pps",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Price per share in microdollars (millionths)",
                        null=True,
                    ),
                ),
                ("latest_409a_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="FundingRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("founding", "Founding / Incorporation"),
                            ("safe", "SAFE / Note Round"),
                            ("seed", "Seed"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B"),
                            ("series_c", "Series C"),
                            ("growth", "Growth / Later Stage"),
                            ("secondary", "Secondary"),
                            ("ipo", "IPO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("close_date", models.DateField()),
                (
                    "pre_money_valuation",
                    models.BigIntegerField(blank=True, help_text="In cents", null=True),
                ),
                (
                    "post_money_valuation",
                    models.BigIntegerField(blank=True, help_text="In cents", null=True),
                ),
                (
                    "amount_raised",
                    models.BigIntegerField(blank=True, help_text="In cents", null=True),
                ),
                (
                    "price_per_share",
                    models.BigIntegerField(blank=True, help_text="In cents", null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="equity.company",
                    ),
                ),
            ],
            options={
                "ordering": ["close_date"],
            },
        ),
        migrations.CreateModel(
            name="VestingSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("time", "Time-based"),
                            ("milestone", "Milestone-based"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="time",
                        max_length=20,
                    ),
                ),
                (
                    "total_months",
                    models.PositiveSmallIntegerField(
                        default=48, help_text="Total vesting period in months"
                    ),
                ),
                (
                    "cliff_months",
                    models.PositiveSmallIntegerField(
                        default=12, help_text="Cliff in months (0 = no cliff)"
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "acceleration",
                    models.CharField(
                        blank=True,
                        help_text="single_trigger / double_trigger / none",
                        max_length=30,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="equity.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vesting Schedule",
            },
        ),
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "holder_type",
                    models.CharField(
                        choices=[
                            ("founder", "Founder"),
                            ("investor", "Investor"),
                            ("employee", "Employee"),
                            ("advisor", "Advisor"),
                            ("board", "Board Member"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("fund", "Investment Fund"),
                            ("trust", "Trust"),
                            ("corp", "Corporation"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="SSN or EIN — store encrypted in production",
                        max_length=20,
                    ),
                ),
                ("is_accredited", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="equity.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked platform account (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stakeholdings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "email")},
            },
        ),
        migrations.CreateModel(
            name="ShareClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(blank=True, max_length=20)),
                (
                    "cls_type",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("preferred", "Preferred"),
                            ("option", "Option"),
                            ("warrant", "Warrant"),
                            ("safe", "SAFE"),
                            ("note", "Convertible Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("authorized_shares", models.BigIntegerField(default=0)),
                (
                    "original_issue_price",
                    models.BigIntegerField(default=0, help_text="In cents"),
                ),
                (
                    "liquidation_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("non_participating", "1× Non-Participating"),
                            ("participating", "Participating"),
                            ("participating_capped", "Participating (Capped)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "liq_pref_multiple",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "conversion_ratio",
                    models.DecimalField(decimal_places=6, default=1, max_digits=10),
                ),
                (
                    "anti_dilution",
                    models.CharField(
                        blank=True,
                        help_text="broad_based_ratchet / full_ratchet / none",
                        max_length=30,
                    ),
                ),
                (
                    "voting_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="votes per share",
                        max_digits=10,
                    ),
                ),
                (
                    "seniority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = most junior; higher = more senior"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="equity.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-seniority", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shares_authorized",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "shares_issued",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "price_per_share",
                    models.BigIntegerField(
                        blank=True,
                        help_text="In microdollars (millionths of a dollar). $0.42 = 420000",
                        null=True,
                    ),
                ),
                ("grant_date", models.DateField(db_index=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="For options: typically 10 years from grant",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("exercised", "Exercised"),
                            ("expired", "Expired"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.TextField(blank=True)),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "board_approval_date",
                    models.DateField(
                        blank=True,
                        help_text="Date board approved this issuance",
                        null=True,
                    ),
                ),
                (
                    "board_approval_ref",
                    models.CharField(
                        blank=True,
                        help_text="Board consent reference number",
                        max_length=100,
                    ),
                ),
                ("form_83b_required", models.BooleanField(default=False)),
                ("form_83b_filed", models.BooleanField(default=False)),
                ("form_83b_filed_at", models.DateField(blank=True, null=True)),
                (
                    "qsbs_eligible",
                    models.BooleanField(
                        blank=True, help_text="Null = not yet evaluated", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="equity.company",
                    ),
                ),
                (
                    "funding_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="equity.fundinground",
                    ),
                ),
                (
                    "share_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="securities",
                        to="equity.shareclass",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="securities",
                        to="equity.stakeholder",
                    ),
                ),
                (
                    "vesting_schedule",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security",
                        to="equity.vestingschedule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Securities",
                "ordering": ["grant_date", "certificate_number"],
            },
        ),
        migrations.AddField(
            model_name="fundinground",
            name="share_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equity.shareclass",
            ),
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shares_exercised",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("exercise_date", models.DateField()),
                (
                    "exercise_price",
                    models.BigIntegerField(
                        help_text="In microdollars — must equal security.price_per_share"
                    ),
                ),
                (
                    "fmv_at_exercise",
                    models.BigIntegerField(
                        blank=True,
                        help_text="409A FMV per share on exercise date, microdollars",
                        null=True,
                    ),
                ),
                (
                    "form_3921_required",
                    models.BooleanField(
                        default=False, help_text="True for ISO exercises"
                    ),
                ),
                ("form_3921_filed", models.BooleanField(default=False)),
                ("form_3921_filed_at", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cashless", "Cashless"),
                            ("net", "Net Exercise"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="equity.company",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises",
                        to="equity.security",
                    ),
                ),
            ],
            options={
                "ordering": ["exercise_date"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("valuation_409a", "409A Valuation Received"),
                            ("rule_701_threshold", "Rule 701 Threshold Crossed"),
                            ("form_83b_filed", "83(b) Election Filed"),
                            ("form_3921_filed", "Form 3921 Filed"),
                            ("qsbs_eval", "QSBS Eligibility Evaluated"),
                            ("board_consent", "Board Consent Obtained"),
                            ("rule_701_disclosure", "Rule 701 Disclosure Delivered"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "value_cents",
                    models.BigIntegerField(
                        blank=True,
                        help_text="409A value, threshold amount, etc.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="equity.company",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.document",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_events",
                        to="equity.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
        migrations.AddIndex(
            model_name="security",
            index=models.Index(
                fields=["company", "status"], name="equity_secu_company_12f615_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="security",
            index=models.Index(
                fields=["company", "grant_date"], name="equity_secu_company_d7252c_idx"
            ),
        ),
    ]
