# Generated by Django 4.2.13 on 2026-08-07 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("equity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True, help_text="e.g. 'Fund I'", max_length=64
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("LP", "Limited Partnership"),
                            ("LLC", "Limited Liability Company"),
                        ],
                        default="LP",
                        max_length=8,
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, default="Valkyrie Capital", max_length=255
                    ),
                ),
                ("vintage_year", models.IntegerField(blank=True, null=True)),
                (
                    "committed_capital",
                    models.BigIntegerField(
                        default=0, help_text="Total LP commitments, in cents"
                    ),
                ),
                ("strategy", models.CharField(blank=True, max_length=255)),
                (
                    "state_of_inc",
                    models.CharField(blank=True, default="Delaware", max_length=64),
                ),
                ("ein", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("safe", "SAFE"),
                            ("note", "Convertible Note"),
                            ("priced", "Priced Equity"),
                            ("interest", "Interest / Direct"),
                            ("token", "Token SAFT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("exited", "Exited / Realized"),
                            ("converted", "Converted (into another position)"),
                            ("superseded", "Superseded / Terminated"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "principal_cents",
                    models.BigIntegerField(
                        default=0, help_text="Amount invested, in cents"
                    ),
                ),
                (
                    "cap_cents",
                    models.BigIntegerField(
                        blank=True, help_text="Valuation cap, in cents", null=True
                    ),
                ),
                ("cap_is_premoney", models.BooleanField(default=False)),
                (
                    "discount_pct",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "interest_rate_pct",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("mfn", models.BooleanField(default=False)),
                ("qsbs", models.BooleanField(default=False)),
                ("round_name", models.CharField(blank=True, max_length=64)),
                (
                    "share_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("num_shares", models.BigIntegerField(blank=True, null=True)),
                ("current_mark_cents", models.BigIntegerField(blank=True, null=True)),
                ("valuation_method", models.CharField(blank=True, max_length=32)),
                ("last_marked", models.DateField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=128)),
                ("ceo_name", models.CharField(blank=True, max_length=128)),
                ("company_contact", models.CharField(blank=True, max_length=255)),
                ("distributions_note", models.TextField(blank=True)),
                ("source_notes", models.TextField(blank=True)),
                ("review_status", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="equity.company",
                    ),
                ),
                (
                    "converted_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_from",
                        to="equity.investment",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="equity.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "company__name"],
                "indexes": [
                    models.Index(
                        fields=["fund", "status"], name="equity_inve_fund_id_f12ec2_idx"
                    ),
                    models.Index(
                        fields=["company"], name="equity_inve_company_d80bff_idx"
                    ),
                ],
            },
        ),
    ]
